# Copyright 2026 HM Revenue & Customs
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

include "frontend.conf"

appName="nova-imports-notification-frontend"

play.http.router = prod.Routes

play.http.errorHandler = "handlers.ErrorHandler"

play.modules.enabled += "uk.gov.hmrc.play.bootstrap.AuthModule"
play.modules.enabled += "uk.gov.hmrc.mongo.play.PlayMongoModule"
play.modules.enabled += "uk.gov.hmrc.play.bootstrap.HttpClientV2Module"
play.modules.enabled += "config.Module"

play.filters.enabled += play.filters.csp.CSPFilter

play.i18n.langs = ["en", "cy"]

microservice {
    services {
      auth {
        protocol = http
        host     = localhost
        port     = 8500
      }

      feedback-frontend {
        protocol = http
        host     = localhost
        port     = 9514
      }

      nova-imports-backend {
        protocol = http
        host     = localhost
        port     = 10301
      }

      address-lookup-frontend {
        protocol = http
        host     = localhost
        port     = 9028
      }
    }
}

contact-frontend {
  host      = "http://localhost:9250"
  serviceId = "nova-imports-notification-frontend"
}

timeout-dialog {
  timeout   = 900
  countdown = 120
}

session {
  timeoutSeconds = 900
}

mongodb {
  uri                 = "mongodb://localhost:27017/"${appName}
  timeToLiveInSeconds = 900
}

urls {
  login         = "http://localhost:9949/auth-login-stub/gg-sign-in"
  loginContinue = "http://localhost:10300/nova-imports"
  signOut       = "http://localhost:9553/bas-gateway/sign-out-without-state"
  importingVehiclesIntoTheUKUrl = "https://www.gov.uk/importing-vehicles-into-the-uk/telling-hmrc#if-you-import-a-vehicle-into-great-britain-from-anywhere-or-into-northern-ireland-from-outside-the-eu"
  euCountriesUrl = "https://www.gov.uk/eu-eea"
  multipleVehiclesSpreadsheetsUrl = "https://www.gov.uk/guidance/telling-hmrc-youre-importing-multiple-vehicles#spreadsheets-for-different-vehicle-types"
  vatNotice728Url = "https://www.gov.uk/guidance/account-for-vat-on-a-new-means-of-transport"
  onlineServicesHelpdeskUrl = "https://www.gov.uk/government/organisations/hm-revenue-customs/contact/online-services-helpdesk"
  technicalSupportUrl = "https://www.gov.uk/find-hmrc-contacts/technical-support-with-hmrc-online-services"
  personalTransportUnitUrl = "https://www.gov.uk/find-hmrc-contacts/personal-transport-unit-enquiries"
  hmrcOnlineAccountAuthorisationUrl = "https://www.gov.uk/guidance/client-authorisation-an-overview"
  onlineAgentAuthorisationUrl       = "https://www.gov.uk/guidance/how-to-use-the-online-agent-authorisation-to-get-authorised-as-a-tax-agent"
}

host = "http://localhost:10300"

accessibility-statement{
  service-path = "/nova-imports-notification-frontend"
}

tracking-consent-frontend {
  gtm.container = "transitional"
}

features {
  welsh-translation: true
}
